### ISSUE TITLE
Console Error Spam

### ISSUE THREAD

**Issue by Maitlans** [ventureoo/BloodFading#1]
Hey, I love the plugin, it's a very cool visual idea for when you get damaged, getting this spammed every few seconds, it seems the plugin works as intended just the error keeps appearing. I'm using 1.18.1 Paper. Thank you

```
[01:30:04 WARN]: [BloodFading] Task #55 for BloodFading v0.5 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
        at ru.ventureo.bloodfading.BloodFadingRunnable.run(BloodFadingRunnable.java:42) ~[BloodFading.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-152]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-152]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-152]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-152]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-152]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-152]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-152]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by ventureoo** [comment]
Hi. I can't reproduce your issue on my Pufferfish 1.18.1, but I can roughly see why it happens. Try this version with the commit https://github.com/ventureoo/BloodFading/commit/63a5ef5d169cce567cc0f61989832aade377029d (Don't forget to uninstall the old version of the plugin). Thanks for the report!
[BloodFading-63a5ef5.zip](https://github.com/ventureoo/BloodFading/files/7957302/BloodFading-63a5ef5.zip)

**Comment by Maitlans** [comment]
Hey thank you, the error appears to be fixed, while testing I found another small issue, for example when pvp is turned off if you mouse click on another player even tho it does no damage it'll still apply the redness around the screen, as well if they're like in /god mode. Not sure if to make another issue thread or whatever you want. Thank you :)

**Comment by ventureoo** [comment]
Oops, I seem to have forgotten that the event can be canceled. Check this version please.

[BloodFading.zip](https://github.com/ventureoo/BloodFading/files/7963532/BloodFading.zip)

**Comment by Maitlans** [comment]
Thank you seems to be working as intended.

**Comment by ventureoo** [comment]
Fine!
