### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by GoodName132** [ventureoo/BloodFading#2]
Version 1.16.5
[07:14:59 WARN]: [BloodFading] Task #700 for BloodFading v0.5.2 generated an exception
java.lang.IllegalArgumentException: Could not find packet for type SET_BORDER_WARNING_DISTANCE
        at com.comphenix.protocol.injector.packet.PacketRegistry.lambda$getPacketClassFromType$0(PacketRegistry.java:379) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.comphenix.protocol.injector.packet.PacketRegistry.getPacketClassFromType(PacketRegistry.java:379) ~[?:?]
        at com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:95) ~[?:?]
        at com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:130) ~[?:?]
        at ru.ventureo.bloodfading.packets.v1_16.ProtocolLibImpl.fading(ProtocolLibImpl.java:38) ~[?:?]
        at ru.ventureo.bloodfading.BloodFadingRunnable.run(BloodFadingRunnable.java:47) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by ventureoo** [comment]
Hi. What version of ProtocolLib do you have installed?

**Comment by ventureoo** [comment]
Never mind. It appears to be a plugin error in version detection. I was sure that starting with 1.16 Minecraft started using the new specification for World Border packets, but I was wrong.

**Comment by ventureoo** [comment]
[BloodFading.zip](https://github.com/ventureoo/BloodFading/files/8708428/BloodFading.zip)
Please check this version.
